### PR TITLE
registerElement

### PR DESCRIPTION
**Pull request by pauloancheta**
## Create a custom element with custom attributes ##
```
function MyElement () {
  return <h1 my-attribute="some value">Hello, World!</h1>
}

Yolk.registerElement( `my-element`, MyElement )
```

### CODE REVIEW

**Comment by jadbox** [comment]
What is this registerElement feature exactly?

**Comment by garbles** [comment]
@jadbox will implement https://github.com/yolkjs/yolk/issues/18

**Comment by garbles** [comment]
@pauloancheta we should also check whether the input is `true` or `false`

**Comment by garbles** [comment]
@pauloancheta :tada: awesome work! I'll write up some documentation for this.

**Comment by pauloancheta** [comment]
:boom: thanks @garbles

**Pull request merged**
