### PR TITLE
Make API sections headered

### PR DESCRIPTION
**Pull request by justinwoo**
This makes them link-able so that I can paste links to specific parts on Twitter 😀

(On my branch it does: https://github.com/justinwoo/yolk/tree/patch-1#yolkcustomcomponent)

### CODE REVIEW

**Comment by garbles** [comment]
Good idea. Any chance you can change them to h5 or h6 so that this will fit on one line?

screen shot 2015-11-10 at 2 28 03 pm

**Comment by justinwoo** [comment]
Looks like it worked with `#####`:

**Comment by garbles** [comment]
@justinwoo thanks! :family:

**Comment by justinwoo** [comment]
:+1: :beers:

**Pull request merged**
